# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
ZiaJobBundle:
    resource: "@ZiaJobBundle/Controller/"
    type:     annotation
    prefix:   /

AcmeDemoBundle:
    resource: "@AcmeDemoBundle/Controller/"
    prefix:   /acme
