<?php

namespace Zia\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function getWithActiveJobsBuilder($category = null)
  {
    $builder = $this->createQueryBuilder('c')
      ->select('c');
    
    $this->addActiveJobsCriteria($builder);
    $this->addCategoryCriteria($builder, $category);
    
    return $builder;
  }

  public function addActiveJobsCriteria($builder)
  {
      $builder->addSelect('j')
      ->leftJoin('c.jobs', 'j' )
      ->where('j.expiresAt > :date')
      ->setParameter('date', date('Y-m-d H:i:s', time()));
  }
  
  public function addCategoryCriteria($builder, $category = null)
  {
    if (!is_null($category)) {
      if (is_numeric($category)) {
        $builder->andWhere('c.id = :category_id')
          ->setParameter('category_id', $category);
      } elseif ($category instanceof Category) {
        $builder->andWhere('c.id = :category_id')
          ->setParameter('category_id', $category->getId());
      } else {
        throw new \Symfony\Component\Validator\Exception\UnexpectedTypeException('Unexpected type of category');
      }
    }
  }
  
  public function addLimit($builder, $maxResults = null)
  {
    if ($maxResults > 0) {
      $builder->setMaxResults($maxResults);
    }
  }

  public function countActiveJobs($category = null)
  {
    $builder = $this->getWithActiveJobsBuilder($category);
    
    $categories = $builder->getQuery()->getResult();
    
    //FIXME: replace this hack with correct count query or paginator
    $num_results = array();
    foreach ($categories as $category) {
      $num_results[$category->getId()] = count($category->getJobs());
    }
    
    return $num_results;
  }
  
  public function findWithActiveJobs($maxResults = null, $category = null)
  {
    $builder = $this->getWithActiveJobsBuilder($category);
    
    $this->addLimit($builder, $maxResults);
    
    return $builder->getQuery()->getResult();    
  }
}