<?php

namespace Zia\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function findWithActiveJobs($maxResults = 10, $category = null)
  {
    $builder = $this->createQueryBuilder('c')
      ->select('c, j')
      ->leftJoin('c.jobs', 'j' )
      ->where('j.expiresAt > :date')
      ->setParameter('date', date('Y-m-d H:i:s', time()));
    
    if (!is_null($category)) {
      if (is_numeric($category)) {
        $builder->andWhere('c.id = :category_id')
          ->setParameter('category_id', $category);
      } elseif ($category instanceof Category) {
        $builder->andWhere('c.id = :category_id')
          ->setParameter('category_id', $category->getId());
      } else {
        throw new \Symfony\Component\Validator\Exception\UnexpectedTypeException('Unexpected type of category');
      }
    }
    
    if ($maxResults) {
      $builder->setMaxResults($maxResults);
    }
    
    return $builder->getQuery()->getResult();    
  }
}