<?php

namespace Zia\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
  public function getActiveJobs()
  {
    return $this->addActiveJobsQuery()->getQuery()->getResult();
  }

  public function addActiveJobsQuery(QueryBuilder $builder = null)
  {
    if ($builder === null)
    {
      $builder = $this->createQueryBuilder('j')
        ->select('j');
    }
    $date = new \DateTime('now');

    $builder->andWhere('j.expiresAt > :date')
      ->andWhere('j.isActivated = 1')
      ->addOrderBy('j.expiresAt', 'DESC')
      ->setParameter('date', $date->format('Y-m-d H:i:s'));

    return $builder;
  }
}