<?php

namespace Zia\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
  public function getActiveJobs()
  {
    return $this->createQueryBuilder('j')
      ->where('j.expiresAt > :date')
      ->orderBy('j.expiresAt', 'DESC')
      ->setParameter('date', date('Y-m-d H:i:s', time() - 86400 * 30))
      ->getQuery()
      ->getResult();
  }
}